# Dependencies
markdown:     rdiscount
permalink:    /:title
highlighter:  pygments

# Settings
destination:  ./_gh_pages
paginate:     6

name:         Taty Grassini
description:  Taty Grassini - Portfolio and Contact info
url:          http://tatygrassini.github.io/