# Dependencies
highlighter:      pygments


# Permalinks
permalink:        /post/:title/


# Settings
destination:      ./_gh_pages
exclude:          ["README.md"]
paginate:         5
encoding:         UTF-8
future:           false
name:             Portfolio
url:              http://tatygrassini.github.io
description:      Taty Grassini's portfolio, Barcelona-based front-end developer specialized in PSD2HTML and PSD2CMS coding.


# Links
expo_repo:        https://github.com/tatygrassini/tatygrassini.github.com/
expo_new_issue:   https://github.com/tatygrassini/tatygrassini.github.com/issues/new
